name: privacyIDEA

services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_USER: pi
      MARIADB_PASSWORD: test123
      MARIADB_DATABASE: pi
      MARIADB_RANDOM_ROOT_PASSWORD: true
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MARIADB_USER --password=$$MARIADB_PASSWORD

  pi:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: "../../"
      dockerfile: ./deploy/docker/Dockerfile
      network: host
    ports:
      - "8080:8080"
    secrets:
      - enckey
      - secret_key
      - pi_pepper
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://pi:test123@db:3306/pi
      FLASK_DEBUG: true
    env_file:
      - ./example.env

secrets:
  enckey:
    # Create a random encryption key with "head -c 96 /dev/urandom > encKey"
    file: ./encKey
  secret_key:
    # Create a suitable secret key with "SECRET_KEY=$(python -c 'import secrets;print(secrets.token_hex())')"
    environment: "SECRET_KEY"
  pi_pepper:
    en
