name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions: {}

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # for actions/first-interaction to comment on first issue
      pull-requests: write  # for actions/first-interaction to comment on first PR
    steps:
    - uses: actions/first-interaction@2d4393e6bc0e2efb2e48fba7e06819c3bf61ffc9 # v2.0.0
      continue-on-error: true
      with:
        issue-message: |
          Thank you for filing an issue and sharing your observations or ideas.
          Please make sure to provide as much information as possible to help us work on this issue.
        pr-message: |
          Thank you for opening a pull-request.
          Please have a look at our contributing guidelines here: [CONTRIBUTING.md](https://github.com/privacyidea/privacyidea/blob/master/CONTRIBUTING.md)
